In [1]:
import sys
import pandas as pd
import numpy as np

In [2]:
from econml.grf import CausalForest

In [3]:
#del sys.modules["helpers"]
#from helpers import msd_one, msd_two, msd_three, inh_str, auto_dummy

In [4]:
#del sys.modules["causal_forest"]
#from causal_forest import ci_crf

In [5]:
#del sys.modules["decompositions"]
from decompositions import fairness_cookbook

In [6]:
data_gov = pd.read_csv('E:/PhD/01_causalfairness/00_codes/gov_census.csv',index_col=0).head(20000)

In [7]:
data_gov[data_gov['sex']=="male"]['salary'].mean() - data_gov[data_gov['sex']=="female"]['salary'].mean()

15053.691747379096

In [8]:
data_gov

sex  age   race hispanic_origin  citizenship      nativity  \
1        male   64  black              no            1        native   
2      female   54  white              no            1        native   
3        male   38  black              no            1        native   
4      female   41  asian              no            1        native   
5      female   40  white              no            1        native   
...       ...  ...    ...             ...          ...           ...   
19996  female   54  white              no            1        native   
19997    male   43  other             yes            4  foreign-born   
19998    male   35   AIAN             yes            4  foreign-born   
19999    male   26  white              no            1        native   
20000    male   58  white             yes            4  foreign-born   

        marital  family_size  children  education_level  english_level  \
1       married            2         0               20              0   
2       married            3         1               20              0   
3       married            3         1               24              0   
4       married            3         1               24              0   
5       married            4         2               21              0   
...         ...          ...       ...              ...            ...   
19996   married            2         0               22              0   
19997  divorced            4         0               21              1   
19998   married            4         2               22              2   
19999   married            2         0               18              0   
20000   married            2         0               19              1   

         salary  hours_worked  weeks_worked occupation  industry  \
1       43000.0            56            49    13-1081      928P   
2       45000.0            42            49    29-2061      6231   
3       99000.0            50            49    25-1000     611M1   
4       63000.0            50            49    25-1000     611M1   
5       45200.0            40            49    27-1010     611M1   
...         ...           ...           ...        ...       ...   
19996   38000.0            40            39    27-3092       923   
19997  100000.0            40            49    33-3021      92MP   
19998   73000.0            40            47    25-2030      6111   
19999   60000.0            75            49    55-2010  928110P4   
20000   56000.0            40            49    17-302X      6111   

      economic_region  
1           Southeast  
2           Southeast  
3           Southeast  
4           Southeast  
5           Southeast  
...               ...  
19996        Far West  
19997        Far West  
19998        Far West  
19999        Far West  
20000        Far West  

[20000 rows x 17 columns]

- fairness cookbook

In [9]:
data = data_gov

#protected class
X = "sex"
#outcome
Y = "salary"
#confounders
Z = np.array(["age","race","hispanic_origin",
             "citizenship","nativity","economic_region"])
#mediators
W = np.array(["marital","family_size","children",
             "education_level","english_level","hours_worked"
             ,"weeks_worked","occupation","industry"])

In [10]:
measure_boots, measure_summary = fairness_cookbook(data = data_gov,
                                  X=X,
                                  Z=Z,
                                  W=W, 
                                  Y=Y, 
                                  x0="female",
                                  x1="male",
                                  method = "causal_forest", 
                                  nboot1 = 1, 
                                  nboot2 = 100,
                                  crf_n_estimators = 100, 
                                  crf_criterion = "mse", 
                                  crf_min_samples_leaf = 5, 
                                  crf_max_features = "sqrt", 
                                  crf_honest = True)

In [11]:
measure_boots

boot         value measure  rep
0    0.0  15267.146075      tv  0.0
1    1.0  15615.297846      tv  0.0
2    2.0  15358.241830      tv  0.0
3    3.0  15075.353006      tv  0.0
4    4.0  14663.595973      tv  0.0
..   ...           ...     ...  ...
95  95.0   -546.409014   ctfie  0.0
96  96.0   -622.336712   ctfie  0.0
97  97.0   -601.858202   ctfie  0.0
98  98.0   -613.149087   ctfie  0.0
99  99.0   -609.421134   ctfie  0.0

[1000 rows x 4 columns]

In [12]:
measure_summary

value            
                  mean         std
measure                           
ctfde     15219.626917   17.364006
ctfie      -605.931536   55.513679
ctfse       730.981469  625.786904
ett       15825.558453   61.316443
expse_x0           NaN         NaN
expse_x1           NaN         NaN
nde       15115.426955   14.036709
nie        -710.131498   59.164031
te        15562.430269   39.574370
tv        15094.576984  611.812710

- ci_helper

In [8]:
data_adj, Z_adj = auto_dummy(data=data_gov.head(10),col=Z)

In [9]:
data_adj

race_asian  race_black  race_white  hispanic_origin_no  nativity_native  \
1            0           1           0                   1                1   
2            0           0           1                   1                1   
3            0           1           0                   1                1   
4            1           0           0                   1                1   
5            0           0           1                   1                1   
6            0           0           1                   1                1   
7            0           0           1                   1                1   
8            0           0           1                   1                1   
9            0           0           1                   1                1   
10           0           0           1                   1                1   

    economic_region_Southeast  age  citizenship     sex   marital  \
1                           1   64            1    male   married   
2                           1   54            1  female   married   
3                           1   38            1    male   married   
4                           1   41            1  female   married   
5                           1   40            1  female   married   
6                           1   46            1  female  divorced   
7                           1   41            1    male   married   
8                           1   54            1    male   married   
9                           1   29            1    male   married   
10                          1   43            1  female   married   

    family_size  children  education_level  english_level   salary  \
1             2         0               20              0  43000.0   
2             3         1               20              0  45000.0   
3             3         1               24              0  99000.0   
4             3         1               24              0  63000.0   
5             4         2               21              0  45200.0   
6             3         1               18              0  28000.0   
7             4         2               21              0  58000.0   
8             2         0               19              0  65000.0   
9             2         0               18              0  32000.0   
10            2         0               18              0   6000.0   

    hours_worked  weeks_worked occupation industry  
1             56            49    13-1081     928P  
2             42            49    29-2061     6231  
3             50            49    25-1000    611M1  
4             50            49    25-1000    611M1  
5             40            49    27-1010    611M1  
6             40            49    43-6014     6111  
7             45            49    13-1070    611M1  
8             55            49    33-3050     92MP  
9             40            49    33-3050     92MP  
10            16            26    43-5031     92MP

In [10]:
Z_adj

array(['race_asian', 'race_black', 'race_white', 'hispanic_origin_no',
       'nativity_native', 'economic_region_Southeast', 'age',
       'citizenship'], dtype=object)

In [9]:
y = np.arange(0,10)

In [10]:
boots = {1:{'all':np.arange(0,10),'id0':[0,1,2],'id1':[3,4,5,6,7,8,9]},
         2:{'all':np.array([0,1,1,2,3,5,6,7,4,9]),'id0':[0,1,1,2],'id1':[3,5,6,7,4,9]}}

In [5]:
pd.DataFrame({'boot':[],
             'value':[],
             'measure':[],
             'rep':[]})

Empty DataFrame
Columns: [boot, value, measure, rep]
Index: []

In [11]:
msd_one(y,"id0","te",boots)

boot  value measure
0     0    1.0      te
1     1    1.0      te

In [12]:
msd_two(y,"id0",-y,"id1","te",boots)

boot     value measure
0     0 -5.000000      te
1     1 -4.666667      te

In [13]:
np.mean([0,1,2])-np.mean([3,4,5,6,7,8,9])

-5.0

In [14]:
np.mean([0,1,1,2])-np.mean([3,5,6,7,4,9])

-4.666666666666667

In [15]:
msd_three(y,"id0",-y,"id1",y,"id1","te",boots)

boot  value measure
0     0    1.0      te
1     1    1.0      te

In [16]:
df_cihelpher = msd_three(y,"id0",-y,"id1",y,"id1","te",boots)

In [17]:
df_cihelpher

boot  value measure
0     0    1.0      te
1     1    1.0      te

In [18]:
inh_str(df_cihelpher,"ctfde",set0=True)

boot  value measure
0     0      0   ctfde
1     1      0   ctfde

In [19]:
inh_str(df_cihelpher,"ctfde",set0=True,setna=True)

boot  value measure
0     0    NaN   ctfde
1     1    NaN   ctfde

- causal forest

In [20]:
test = 1 if False else 2

In [21]:
test

2

In [22]:
np.random.randint(0,df_cihelpher.shape[0],df_cihelpher.shape[0])

array([1, 1])

In [23]:
df_cihelpher.shape[0]

2

In [24]:
np.arange(0,df_cihelpher.shape[0])

array([0, 1])

In [25]:
data_gov_head = data_gov.head(10)

In [26]:
data = data_gov_head
nrow_df = data.shape[0]
print(data.shape[0])
rep = 1
nboot = 5
x0="female"
X = "sex"

boot_samp = np.random.randint(0,nrow_df,nrow_df) if rep>1 else np.arange(0,nrow_df)  
boot_data = data.iloc[boot_samp,:].reset_index(drop=True)

nrow_boot_df = boot_data.shape[0]
boots = dict.fromkeys(np.arange(nboot))
for key in boots:
    boots[key] = dict.fromkeys(["all","id0","id1"])
    ind = np.random.randint(0,nrow_boot_df,nrow_boot_df)

    idx0 = boot_data[X][ind] == x0
    ind0 = ind[idx0]
    ind1 = ind[~idx0]

    boots[key]["all"] = ind
    boots[key]["id0"] = ind0
    boots[key]["id1"] = ind1

10


In [27]:
boot_data[X][ind]

6      male
7      male
5    female
1    female
2      male
8      male
5    female
7      male
9    female
7      male
Name: sex, dtype: object

In [28]:
boots

{0: {'all': array([9, 4, 6, 9, 9, 5, 4, 4, 3, 9]),
  'id0': array([9, 4, 9, 9, 5, 4, 4, 3, 9]),
  'id1': array([6])},
 1: {'all': array([3, 5, 7, 4, 6, 1, 7, 6, 7, 1]),
  'id0': array([3, 5, 4, 1, 1]),
  'id1': array([7, 6, 7, 6, 7])},
 2: {'all': array([1, 6, 1, 1, 2, 5, 8, 1, 0, 3]),
  'id0': array([1, 1, 1, 5, 1, 3]),
  'id1': array([6, 2, 8, 0])},
 3: {'all': array([8, 1, 0, 6, 9, 5, 3, 0, 6, 3]),
  'id0': array([1, 9, 5, 3, 3]),
  'id1': array([8, 0, 6, 0, 6])},
 4: {'all': array([6, 7, 5, 1, 2, 8, 5, 7, 9, 7]),
  'id0': array([5, 1, 5, 9]),
  'id1': array([6, 7, 2, 8, 7, 7])}}

In [29]:
Y = "salary"

In [30]:
y = boot_data[Y].astype(float)

In [31]:
tv = msd_two(y, "id1", -y, "id0", "tv", boots)    

In [32]:
tv

boot         value measure
0     0  30155.555556      tv
1     1  16960.000000      tv
2     2  12833.333333      tv
3     3   5800.000000      tv
4     4  37250.000000      tv

In [33]:
[1]*10

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [37]:
np.array([tv['value'][0]]*data.shape[0])

array([30155.55555556, 30155.55555556, 30155.55555556, 30155.55555556,
       30155.55555556, 30155.55555556, 30155.55555556, 30155.55555556,
       30155.55555556, 30155.55555556])

In [39]:
boot_data[Y].astype(float).values

array([43000., 45000., 99000., 63000., 45200., 28000., 58000., 65000.,
       32000.,  6000.])

In [40]:
data_gov_head

sex  age   race hispanic_origin  citizenship nativity   marital  \
1     male   64  black              no            1   native   married   
2   female   54  white              no            1   native   married   
3     male   38  black              no            1   native   married   
4   female   41  asian              no            1   native   married   
5   female   40  white              no            1   native   married   
6   female   46  white              no            1   native  divorced   
7     male   41  white              no            1   native   married   
8     male   54  white              no            1   native   married   
9     male   29  white              no            1   native   married   
10  female   43  white              no            1   native   married   

    family_size  children  education_level  english_level   salary  \
1             2         0               20              0  43000.0   
2             3         1               20              0  45000.0   
3             3         1               24              0  99000.0   
4             3         1               24              0  63000.0   
5             4         2               21              0  45200.0   
6             3         1               18              0  28000.0   
7             4         2               21              0  58000.0   
8             2         0               19              0  65000.0   
9             2         0               18              0  32000.0   
10            2         0               18              0   6000.0   

    hours_worked  weeks_worked occupation industry economic_region  
1             56            49    13-1081     928P       Southeast  
2             42            49    29-2061     6231       Southeast  
3             50            49    25-1000    611M1       Southeast  
4             50            49    25-1000    611M1       Southeast  
5             40            49    27-1010    611M1       Southeast  
6             40            49    43-6014     6111       Southeast  
7             45            49    13-1070    611M1       Southeast  
8             55            49    33-3050     92MP       Southeast  
9             40            49    33-3050     92MP       Southeast  
10            16            26    43-5031     92MP       Southeast

In [45]:
from sklearn import preprocessing

In [47]:
x0

'female'

In [48]:
np.where(boot_data["sex"]==x0,0,1)

array([1, 0, 1, 0, 0, 0, 1, 1, 1, 0])

In [44]:
boot_data["sex"]

1       male
2     female
3       male
4     female
5     female
6     female
7       male
8       male
9       male
10    female
Name: sex, dtype: object

In [50]:
boot_data = data_gov_head
crf_tmp = CausalForest()
crf_tmp.fit(X = boot_data[['citizenship']].values, T = np.where(boot_data['sex'].values==x0,0,1), y = y.values)
crf_te = crf_tmp.oob_predict( boot_data[['citizenship']].values)

In [55]:
crf_te.ravel()

array([25161.23876124, 31228.69458128, 12567.4796748 , 28800.        ,
       24065.62847608, 25806.25814863, 23315.70391872, 26654.65201465,
       32585.39371685, 19791.66666667])

In [56]:
crf_te

array([[25161.23876124],
       [31228.69458128],
       [12567.4796748 ],
       [28800.        ],
       [24065.62847608],
       [25806.25814863],
       [23315.70391872],
       [26654.65201465],
       [32585.39371685],
       [19791.66666667]])

In [58]:
np.concatenate([[0],["1"]])

array(['0', '1'], dtype='<U11')

In [59]:
data_gov_head

sex  age   race hispanic_origin  citizenship nativity   marital  \
1     male   64  black              no            1   native   married   
2   female   54  white              no            1   native   married   
3     male   38  black              no            1   native   married   
4   female   41  asian              no            1   native   married   
5   female   40  white              no            1   native   married   
6   female   46  white              no            1   native  divorced   
7     male   41  white              no            1   native   married   
8     male   54  white              no            1   native   married   
9     male   29  white              no            1   native   married   
10  female   43  white              no            1   native   married   

    family_size  children  education_level  english_level   salary  \
1             2         0               20              0  43000.0   
2             3         1               20              0  45000.0   
3             3         1               24              0  99000.0   
4             3         1               24              0  63000.0   
5             4         2               21              0  45200.0   
6             3         1               18              0  28000.0   
7             4         2               21              0  58000.0   
8             2         0               19              0  65000.0   
9             2         0               18              0  32000.0   
10            2         0               18              0   6000.0   

    hours_worked  weeks_worked occupation industry economic_region  
1             56            49    13-1081     928P       Southeast  
2             42            49    29-2061     6231       Southeast  
3             50            49    25-1000    611M1       Southeast  
4             50            49    25-1000    611M1       Southeast  
5             40            49    27-1010    611M1       Southeast  
6             40            49    43-6014     6111       Southeast  
7             45            49    13-1070    611M1       Southeast  
8             55            49    33-3050     92MP       Southeast  
9             40            49    33-3050     92MP       Southeast  
10            16            26    43-5031     92MP       Southeast

In [62]:
pd.concat([data_gov_head,data_gov_head,data_gov_head,data_gov_head])

sex  age   race hispanic_origin  citizenship nativity   marital  \
1     male   64  black              no            1   native   married   
2   female   54  white              no            1   native   married   
3     male   38  black              no            1   native   married   
4   female   41  asian              no            1   native   married   
5   female   40  white              no            1   native   married   
6   female   46  white              no            1   native  divorced   
7     male   41  white              no            1   native   married   
8     male   54  white              no            1   native   married   
9     male   29  white              no            1   native   married   
10  female   43  white              no            1   native   married   
1     male   64  black              no            1   native   married   
2   female   54  white              no            1   native   married   
3     male   38  black              no            1   native   married   
4   female   41  asian              no            1   native   married   
5   female   40  white              no            1   native   married   
6   female   46  white              no            1   native  divorced   
7     male   41  white              no            1   native   married   
8     male   54  white              no            1   native   married   
9     male   29  white              no            1   native   married   
10  female   43  white              no            1   native   married   
1     male   64  black              no            1   native   married   
2   female   54  white              no            1   native   married   
3     male   38  black              no            1   native   married   
4   female   41  asian              no            1   native   married   
5   female   40  white              no            1   native   married   
6   female   46  white              no            1   native  divorced   
7     male   41  white              no            1   native   married   
8     male   54  white              no            1   native   married   
9     male   29  white              no            1   native   married   
10  female   43  white              no            1   native   married   
1     male   64  black              no            1   native   married   
2   female   54  white              no            1   native   married   
3     male   38  black              no            1   native   married   
4   female   41  asian              no            1   native   married   
5   female   40  white              no            1   native   married   
6   female   46  white              no            1   native  divorced   
7     male   41  white              no            1   native   married   
8     male   54  white              no            1   native   married   
9     male   29  white              no            1   native   married   
10  female   43  white              no            1   native   married   

    family_size  children  education_level  english_level   salary  \
1             2         0               20              0  43000.0   
2             3         1               20              0  45000.0   
3             3         1               24              0  99000.0   
4             3         1               24              0  63000.0   
5             4         2               21              0  45200.0   
6             3         1               18              0  28000.0   
7             4         2               21              0  58000.0   
8             2         0               19              0  65000.0   
9             2         0               18              0  32000.0   
10            2         0               18              0   6000.0   
1             2         0               20              0  43000.0   
2             3         1               20              0  45000.0   
3             3         1               24              0  990